[package]
name = "rc-control"
version = "0.1.0"
authors = ["Daniel Olano <danielolanoc@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = { version = "0.2.3", features = ["unproven"] }
rppal = { version = "0.11.3", features = ["hal"] }
